### PR TITLE
Add f2fs support and fix some missing change.

### PR DESCRIPTION
**Pull request by joe820730**

### CODE REVIEW

**Comment by GuaiYiHu** [comment]
No need to add f2fs support now.

**Comment by joe820730** [comment]
This kernel supports f2fs and have been enabled. it tested on my device.

**Comment by GuaiYiHu** [comment]
Not only in fstab, but also in boardconfig.mk. So let's make other blobs work rather than add new functions.

**Comment by GuaiYiHu** [comment]
Just like this commit https://github.com/djeman/android_device_samsung_j3xnlte/commit/fe51e2e8f234fb36ddaec81e605ec442424b757e

**Pull request closed without merging**
